import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { GetServerSideProps, NextPage } from "next";

type PhotoType = {
  id: number;
  url: string;
  author: string;
};

interface Props {
  data: PhotoType[];
}

const Home: NextPage<Props> = ({ data }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <ul>
            {data?.map((data) => (
              <li key={data.id}>
                <img
                  src={data.url}
                  alt={data.author}
                />
                <h6>{data.author}</h6>
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch("https://picsum.photos/v2/list");
  const data = await res.json();
  console.log(data);
  return {
    props: { data },
  };
};

export default Home;
